### ISSUE TITLE
Create initial draft

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#1]
Parent issue is https://github.com/phetsims/chipper/issues/479

**Comment by samreid** [comment]
For example, look at FunctionBuilderQueryParameters for a situation where the multi-schema would be appropriate.  Keep the QueryStringMachine.get('',{}) for single string cases.

**Comment by samreid** [comment]
When trying to exercise QueryStringMachine for FunctionBuilder, I noticed that the string keys will not match.  For instance FBQueryParameters has:

```js
SLOW: !!getQueryParameter( 'slow' ),
```

But unless we do something about it, QueryStringMachine would have:

```js
slow: {type:'flag'},
```

If we changed QueryStringMachine to be:
```js
SLOW:{type:'flag'}
```
then the query parameter must be supplied as ?SLOW=true

My recommendation is to use lower/camel case and enforce matching of strings.  @pixelzoom please let me know whether this will be acceptable.

**Comment by pixelzoom** [comment]
> My recommendation is to use lower/camel case and enforce matching of strings. @pixelzoom please let me know whether this will be acceptable.

👍

**Comment by samreid** [comment]
Initial draft completed.  I'll create next issue for review.
