### ISSUE TITLE
// TODO: validate arrays

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#11]
From #9 we would like to make sure that arrays can be validated (or documented as un-validateable).  However, since QSM supports arrays of arrays of arrays, we may need a recursive implementation for this.  That is, `===` won't work for arrays at any level.

**Comment by samreid** [comment]
@andrewadare: In discussing https://github.com/phetsims/special-ops/issues/40 with @ariel-phet, he suggested it would be good for you to look into this, partly so that we can share knowledge about Query String Machine and also so it can benefit from another pair of eyes.  We already have validation for primitive types for both `allowedValues` and `validate`, please see the manual and automated tests here: query-string-machine/test-query-string-machine.html

However, we would like to add support for validation for arrays.  Can you add an automated test like this?
* An array must have exactly 3 elements
* An array of integers must sum to 7
* etc.

Then add support in QueryStringMachine.js to catch the errors during validation.

After that is working, see if it is feasible to generalize to validating arrays of arrays.  Please let me or @pixelzoom know if you have any questions or suggestions.

**Comment by andrewadare** [comment]
@samreid Do you have any objections to moving the js code inside the `<script>` tags into a js file called test/testQueryStringMachine.js, and calling the UMD module as an IIFE?

In my opinion, this would improve maintainability as new tests are added.

**Comment by andrewadare** [comment]
I've done this by the way (but not committed).

**Comment by samreid** [comment]
> and calling the UMD module as an IIFE?

Can you explain how this part would work?

**Comment by andrewadare** [comment]
I simply appended () to the end to call the function:

```js
// Copyright 2016, University of Colorado Boulder

// UMD, see https://github.com/umdjs/umd/blob/master/templates/returnExports.js
( function( root, factory ) {
  'use strict';

...


} )();
```

then loaded the script as usual:

```html
<head>
  <script type="text/javascript" src="js/QueryStringMachine.js"></script>
  <script type="text/javascript" src="js/test/testQueryStringMachine.js"></script>
</head>
```

**Comment by samreid** [comment]
OK with me to move test code to a separate js file, in an IIFE.

**Comment by andrewadare** [comment]
@samreid refactor complete, now ready to proceed with array validation code.

**Comment by samreid** [comment]
I reformatted with IDEA, please pull before you proceed.

**Comment by andrewadare** [comment]
@samreid I'm trying to understand how this works:

> We already have validation for primitive types for both allowedValues and validate, please see the manual and automated tests ...

I see that there is a `validate()` function for `name` in one of the main schema objects used for the automated tests:

```js
  var schemaMap = {
    height: {
      type: 'number',
      defaultValue: 6,
      allowedValues: [ 4, 5, 6, 7, 8 ]
    },
    name: {
      type: 'string',
      defaultValue: 'Larry',
      validate: function( str ) {
        testAssert( str.indexOf( 'Z' ) !== 0, 'Name cannot start with Z: ' + str );
      }
    },
...
```
schemaMap.name.validate() is never used, though. If I visit the test page with a query parameter that violates the test (say, test-query-string-machine.html?name=zoompixel), no assertion is thrown.

Should there be a check for the existence of a validate() function for each key, then a call if it exists? Should that code be part of the test harness, or QueryStringMachine itself? Sorry for the confusion here.

**Comment by pixelzoom** [comment]
@andrewadare In https://github.com/phetsims/query-string-machine/issues/13, the validation option names were changed from `allowedValues` and `validate` to `validValues` and `isValidValue` respectively.  Looks like I missed the unit tests.

So I fixed the unit tests above, and now they're failing here:

```js
     isValidValue: function( str ) {
        testAssert( false, 'Assert message' );
      }
```

I don't understand a couple of things here, perhaps @samreid can clarify:

(1) What is the above test trying to accomplish? There's no possible way that it can succeed.
(2) Why aren't we using qunit, as we are for axon, etc?  We don't need yet-another unit-test pattern.

**Comment by andrewadare** [comment]
@pixelzoom this makes so much more sense now! I added that test above, while trying to figure things out. It was meant to trigger an assertion failure (and never did). Now that I understand what's going on, I'll update it to something meaningful.

@samreid and I were discussing qunit today, and he mentioned that it seemed like overkill at this stage. However, I think everyone would support using it here.

**Comment by pixelzoom** [comment]
@andrewadare said:
>  I added that test above, while trying to figure things out. It was meant to trigger an assertion failure (and never did). Now that I understand what's going on, I'll update it to something meaningful.

I hit this bogus assertion again while working on #16, and it makes this test harness unusable. So I changed your test to return true for now, and added a TODO for you in the code.

**Comment by andrewadare** [comment]
> An array of integers must sum to 7

I added the test above. QSM runs the test, and when it fails, the test harness catches the error. @samreid or @pixelzoom, can one of you review this and see if it is being done correctly? 

It was mentioned to support recursion to arbitrary depth (e.g. for multidimensional arrays, or arrays of arrays). I did not try this, but would like to check what was done before going further.

**Comment by samreid** [comment]
I changed the defaultValue to `defaultValue: [ 1, 6 ],` and ran the test.  Then I received this error:

`missing query parameter should be caught`

That error doesn't sound quite right.  Should it read: "Test for error handling failed because no error was found"?

**Comment by andrewadare** [comment]
@samreid Thanks for catching that, it was a copy-paste error. I changed the default value to satisfy the test, and the input value to trigger a failure. I also fixed the message and added some clarifying comments to the test, since the logic is "backwards" at first glance (it's not typical to assert an error!)

**Comment by andrewadare** [comment]
Also, I want to add the test page to @jonathanolson's new phetmarks page for easy reference. Any objections?

**Comment by samreid** [comment]
> Also, I want to add the test page to @jonathanolson's new phetmarks page for easy reference. Any objections?

Please proceed.

**Comment by pixelzoom** [comment]
@andrewadare I'm deleting your "minefield" test case from testQueryStringMachine.js.  It's been broken since 10/27/16, and it's affecting my ability to properly test #20.

**Comment by samreid** [comment]
@pixelzoom says this is no longer relevant, closing.
