### ISSUE TITLE
change validation option names to match Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#13]
See https://github.com/phetsims/axon/issues/101#issuecomment-250249043

Change is:

allowedValues -> validValues
validate -> isValidValue

**Comment by pixelzoom** [comment]
Changed and tested in function-builder.  But I have no idea how to go about testing in phet-io (which seems to be a chronic problem whenever I need to touch something in PhET-iO).  @samreid?

**Comment by samreid** [comment]
The only occurrence of `validValues` or `isValidValue` in phet-io is

```js
  var solution = QueryStringMachine.get( 'solution', {
    type: 'string',
    defaultValue: 'drinkMix',
    validValues: [ 'drinkMix', 'cobaltIINitrate', 'cobaltChloride', 'potassiumDichromate', 'potassiumChromate', 'nickelIIChloride', 'copperSulfate', 'potassiumPermanganate', 'sodiumChloride' ]
  } );
```

I'll try launching that wrapper with a different solution.  I launched:
http://localhost/phet-io/wrappers/lab-book/lab-book.html?sim=beers-law-lab&solution=hello
and saw:
```
Error for query parameter "solution": value not allowed: hello, validValues: ["drinkMix","cobaltIINitrate","cobaltChloride","potassiumDichromate","potassiumChromate","nickelIIChloride","copperSulfate","potassiumPermanganate","sodiumChloride"]
```

So phet-io tests out OK.

> I have no idea how to go about testing in phet-io (which seems to be a chronic problem whenever I need to touch something in PhET-iO)

I'll create a phet-io issue regarding this.

**Comment by pixelzoom** [comment]
@samreid If there's nothing else to do here, feel free to close.
