### ISSUE TITLE
Support UMD

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#14]
@zepumph and I would like to support UMD for using QueryStringMachine in node

**Comment by zepumph** [comment]
var scope;

// if the module has no dependencies, the above pattern can be simplified to
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    scope = global;
    module.exports = factory();
  } else {
    // Browser globals (root is window)
    scope = window;
    root.returnExports = factory();
  }
}(this, function () {

  // Just return a value to define the module export.
  // This example returns an object, but the module
  // can return a function as the exported value.
  return QueryStringMachine;
}));

**Comment by samreid** [comment]
Working well, closing.
