### ISSUE TITLE
Replace all phet.chipper.getQueryParameter usages with QueryStringMachine

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#15]
For instance:

test-sims.js has:

``` js
var task = phet.chipper.getQueryParameter( 'testTask' ) || 'none';
```

this would be replaced with:

``` js
var task = QueryStringMachine.get( 'testTask',{type:'string',defaultValue:'none'} );
```

**Comment by samreid** [comment]
A significant problem is for flags like `?useFeature=false` where `"false"` is being interpreted as truthy.

@zepumph suggested raising this for developer meeting, we may proceed by having each developer take some of the work.

**Comment by samreid** [comment]
@andrewadare suggested each developer should fix their own cases, because they will be better able to test the changes (because they are more familiar with their own codebases).

**Comment by pixelzoom** [comment]
Done for all of my sims.

Two observations:

(1) It would be nice to have a way to get state of the `dev` query parameter without having to repeat `dev: { type: 'flag' }`.  Perhaps we need JoistQueryParameters?

(2) To enable logging, some sims check `phet.chipper.getQueryParameter( 'log' )` in their namespace file.  See for example functionBuilder.js.  FBQueryParameters can't be loaded here because that would require functionBuilder.js to be namespaced, and it can't namespace itself.  How (or should) we address this?

**Comment by samreid** [comment]
> FBQueryParameters can't be loaded here because that would require functionBuilder.js to be namespaced, and it can't namespace itself.

I'm confused about the logic here.  It seems like the true problem is that functionBuilder.js must be loaded before FBQueryParameters is loaded, so that namespace be used in FBQueryParameters.  Hence it would introduce a cyclic dependency.

**Comment by pixelzoom** [comment]
Right.

**Comment by jonathanolson** [comment]
It also looks like initialize-globals now depends on QueryStringMachine? I'm fine taking care of usages I'm familiar with.

**Comment by pixelzoom** [comment]
To address this issue:

> (2) To enable logging, some sims check phet.chipper.getQueryParameter( 'log' ) in their namespace file. See for example functionBuilder.js. FBQueryParameters can't be loaded here because that would require functionBuilder.js to be namespaced, and it can't namespace itself. How (or should) we address this?

I moved the logging flag from the namespace file (e.g. functionBuilder.js):

```js
  // enables logging output to the console
  if ( phet.chipper.getQueryParameter( 'log' ) ) {
    console.log( 'enabling log' );
    functionBuilder.log = function( message ) {
      console.log( '%clog: ' + message, 'color: #009900' ); // green
    };
  }
```

... to the query parameters file (e.g. FBQueryParameters):

```js
    // enables console logging
    log: { type: 'flag' }
```

Usages change from this:

```js
functionBuilder.log && functionBuilder.log( message );
```

... to this:

```js
FBQueryParameters.log && console.log( message );
```

The upside is that all query parameters are now documented and processed in one place. The downside is that the color-coding of log messages is lost.

**Comment by samreid** [comment]
> It also looks like initialize-globals now depends on QueryStringMachine?

QSM is now included in every simulation, but I don't see any references to it in initialize-globals.js, am I missing something?

**Comment by pixelzoom** [comment]
@samreid You may want to review https://github.com/phetsims/beers-law-lab/commit/087f9e1ba4e169aa946ecc0a72287d806fe4a991, since Beers Law Lab has some query parameters that are used by PhET-iO.

**Comment by pixelzoom** [comment]
@samreid You may want to review phetsims/beers-law-lab@087f9e1, since Beers Law Lab has some query parameters that are used by PhET-iO.  I did test all query parameters and they appeared to behave as expected.

**Comment by pixelzoom** [comment]
The following common-code repositories use `getQueryParameter`. We should decide which ones to convert to `QueryStringParameter`, and put developer names next to them.

- [ ] brand
- [ ] chipper
- [ ] joist
- [ ] phet-io
- [ ] phetcommon
- [ ] scenery-phet
- [ ] sun
- [ ] tandem

**Comment by pixelzoom** [comment]
I also notice:

(4) For `type: 'number'` there are some common validations (range, integer) that the `validValues` option doesn't support well or at all.  So the client end up needing to do validation outside of `QueryStringMachine`, something like this:

```js
var MyQueryParameters = QueryStringMachine.getAll( {
  numberOfWidgets: { type: 'number' }
} );

assert && assert( MyQueryParameters.numberOfWidgets > 0 && MyQueryParameters.numberOfWidgets <= 100

return MyQueryParameters;
```

I think it would be useful to add something to `QueryStringMachine` to support this.

**Comment by jonathanolson** [comment]
> QSM is now included in every simulation, but I don't see any references to it in initialize-globals.js, am I missing something?

It includes getQueryParameter calls for brand and locale, which would be converted to QSM, correct?

**Comment by samreid** [comment]
> So the client end up needing to do validation outside of `QueryStringMachine`

Can you use `isValidValue` like this:

https://github.com/phetsims/query-string-machine/blob/438cfac1d9a37981ae6d9166a657b44915e1f018/js/test/testQueryStringMachine.js#L19-L25

**Comment by pixelzoom** [comment]
Ah, thanks, missed that.

**Comment by samreid** [comment]
> It includes getQueryParameter calls for brand and locale, which would be converted to QSM, correct?

Yes, initialize-globals should be rewritten to use QueryStringMachine.

**Comment by pixelzoom** [comment]
There's a problem with `isValueValue`, tracking in #16.

**Comment by jessegreenberg** [comment]
@andrewadare suggested that we add a query parameter to find deprecated uses of ```getQueryParameter```.

**Comment by jessegreenberg** [comment]
@pixelzoom volunteered to tackle joist.

**Comment by pixelzoom** [comment]
Other 10/27/16 notes: 
• Add `@deprecated` annotation to getQueryParameter
• No new code should use getQueryParameter
• Convert to QueryStringMachine as we go

**Comment by pixelzoom** [comment]
Query parameters for all "post-load" common code will be consolidated in chipper.QueryParameters. See phetsims/chipper#516.

**Comment by pixelzoom** [comment]
I created a separate issue for each converting each sim to QueryStringMachine, to be addressed by the primary sim developer.

**Comment by pixelzoom** [comment]
I converted all sims that had a *QueryParameters.js file, but didn't do the ones that don't follow PhET convention for query parameters.

**Comment by pixelzoom** [comment]
Closing this issue. There are separate issues for each sim (see above), and for common code (https://github.com/phetsims/chipper/issues/516).
