### ISSUE TITLE
Make it possible to enter empty arrays

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#17]
From https://github.com/phetsims/make-a-ten/issues/231

Can we support empty arrays like this:

```
http://my.url.com/sim.html?exploreNumbers=&otherQueryString
http://my.url.com/sim.html?exploreNumbers=
```

**Comment by pixelzoom** [comment]
We are currently requiring all non-flag types to have an explicit value. What should arrays be different, what is the use case for an empty array?

**Comment by samreid** [comment]
The first use case was identified 20 days ago in this issue comment: https://github.com/phetsims/make-a-ten/issues/231#issuecomment-256841873

**Comment by pixelzoom** [comment]
That case can be addressed by:

```js
if ( QueryStringMachine.containsKey( 'exploreNumbers' ) ) {
   var exploreNumbers = QueryStringMachine.get( {
    type: 'array',
    ...
   } );
}
```

**Comment by samreid** [comment]
> We are currently requiring all non-flag types to have an explicit value. Why should arrays be different

Any empty array is an explicit value, even if it is specified using an odd syntax ?myArray=&otherValue.  It looks odd because we don't require brackets around the arrays.  If we used ?myArray=[]&otherValue it might have been clearer, but I like ?screens=1,2 too much to change it to ?screens=[1,2].  It seems reasonable to me that QSM should be able to support empty arrays.  I'll look into this issue when I have time.

**Comment by samreid** [comment]
QSM now supports empty arrays, such as ?hello&screens=&webgl=false

@jonathanolson can you please test this in your context?

**Comment by jonathanolson** [comment]
Working great, thanks!
