### ISSUE TITLE
Review initial draft.

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#2]
In #1 I completed the initial draft of QueryStringMachine.  The public API was reviewed in https://github.com/phetsims/function-builder/issues/101 and Function Builder is using this for its query parameters as a test case.  I also added QueryStringMachine manual and automated tests, see the documentation in README.md.  The next step is to review the QueryStringMachine itself. After that review is complete, we can start using it more broadly in our applications.

@pixelzoom since you already have some familiarity, could you review this?  If you haven't time, please let me know and we'll schedule someone else.

**Comment by samreid** [comment]
I added some missing docs in the above commit.

**Comment by pixelzoom** [comment]
Many changes and TODO items in above commits (following an ugly, botched merge).  Let me know if you want to discuss.

**Comment by samreid** [comment]
In the preceding commits, I addressed this TODO:

```//TODO Can't lint this, repo is missing standard files (Gruntfile, .gitignore, ...)```

**Comment by samreid** [comment]
@pixelzoom said:

> //TODO Does this need a namespace? Does this repo have a namespace?

Like assert.js, this repo does not require a Namespace instance.

**Comment by samreid** [comment]
@pixelzoom said:

> //TODO Since we don't have control over what the user enters for the parameter string, assertions herein should probably be changed to Errors

I opted for assertions because (a) they match the rest of PhET convention for argument checking (b) they can be stripped and (c) they are 1-line easy to read/write/maintain.

I think you are saying that we would want to prevent the application from launching if the allowed values are [1,2,3] and the user supplied [-1], for instance *whether or not ?ea is specified*.  This seems like good reasoning.  I'll create a separate issue for that.

**Comment by samreid** [comment]
@pixelzoom said:

```js
var value = Number( string ); //TODO This looks suspicious. Should this be new Number? Should we be using Number?
```
I was following the MDN examples from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number in the "Convert numeric strings to numbers" section.

**Comment by samreid** [comment]
> //TODO are we returning number or Number here?

Number('123') returns number

![image](https://cloud.githubusercontent.com/assets/679486/18408232/43a126f4-76e7-11e6-97ec-58048777e85f.png)

**Comment by samreid** [comment]
In the preceding commit, I added `allowedValues` support for `array`.  I chose the semantics to be "the allowed value of the entire array" (to match convention with the other types) and not "allowed values for individual elements".  If we have a need for the latter in the future, we could add it by adding `allowedElementValues`.

**Comment by samreid** [comment]
@pixelzoom said:

```js
// TODO: make sure schema.defaultValue matches schema.type (how to do that if parse is provided instead of type?)
```

My suggestion is for both values to be validated in the call to:
```js
validateValue( value, schema );
```
which is currently done.  Is that insufficient?

**Comment by samreid** [comment]
I finished addressing the TODOs marked in the file, thanks for suggesting these improvements.  Some of the TODOs were raised for discussion in the preceding comments.  Back to @pixelzoom for discussion.

**Comment by pixelzoom** [comment]
Changes look good. Fixed some jsdoc in above commits.

Re validation of `defaultValue` as proposed in https://github.com/phetsims/query-string-machine/issues/2#issuecomment-246208018.  Yes, that sounds good.  But for testing purposes, `defaultValue` will only get checked when a value is omitted, so it's possible that there might be a problem with the default value that goes unnoticed.  Should the full schema be validated regardless of the parameter string?

**Comment by samreid** [comment]
> But for testing purposes, defaultValue will only get checked when a value is omitted, so it's possible that there might be a problem with the default value that goes unnoticed. Should the full schema be validated regardless of the parameter string?

Originally I thought that should occur during a testing or assertion phase, not every time the production sim is run.  But since it should be extremely fast, we can have it run every time. I'l create a new issue for that.

**Comment by pixelzoom** [comment]
> Originally I thought that should occur during a testing or assertion phase

Assertions sounds most appropriate, since the schema isn't something the user can change. But if it's easier to validate via user-Error checking, go for it.

**Comment by samreid** [comment]
Thanks, I moved your comment to the related issue, closing.
