### ISSUE TITLE
Errors in repositories without lodash dependencies

### ISSUE THREAD

**Issue by mattpen** [phetsims/query-string-machine#25]
When running wrappers in phet-io that rely on QSM, we get an error:

`Uncaught ReferenceError: _ is not defined` @ https://github.com/phetsims/query-string-machine/blob/5b8a2418e8e331c3102c380f7f8b14ee91e61321/js/QueryStringMachine.js#L489

According to @samreid, this could affect other repos too, such as aqua, that are not currently dependent on lodash.

Should we require lodash in repos that use QSM, or can we include lodash in QSM? 

@samreid @pixelzoom thoughts?

**Comment by samreid** [comment]
I decided to add lodash to QSM because our sims already use lodash and we needed to do deep-equals.  I forgot that our wrappers use QSM and do not already use lodash as a convention.  I wonder if I should write my own deep equals, or if we will require all wrappers to use lodash.

**Comment by samreid** [comment]
> include lodash in QSM?

I don't think we can do that because of a licensing conflict.

**Comment by samreid** [comment]
Here is the line from lodash we are using:

```js
found = _.isEqual( validValues[i], value ); //TODO can we use lodash?
```

**Comment by pixelzoom** [comment]
lodash dependency was added by @samreid in https://github.com/phetsims/query-string-machine/commit/2bc3c25a0285e40a2ef9f4ced5f4b4c045f0ccfb.

I noticed this while working on #20, and it seems incompatible with the documented goals of "". So I noted in https://github.com/phetsims/query-string-machine/issues/20#issuecomment-264321089 and added this TODO item for discussion:

```488 found = _.isEqual( validValues[i], value ); //TODO can we use loads?```

**Comment by zepumph** [comment]
Another thought is that since we give QSM to 3rd party wrapper devs, they will need lodash as well as phetio.js

**Comment by pixelzoom** [comment]
Rather than depend on lodash, can we write our own equivalent of `_.isEqual` that does deep comparison?

**Comment by pixelzoom** [comment]
Why do we need explicit support for Date in `deepEquals`? (added in https://github.com/phetsims/query-string-machine/commit/96bd261dd59071b7c9b761f0efe9998b17a87ddd).  A query parameter whose value is  a Date would be type 'custom'.   And I would think that would be handled by the client in `isValidValue`. If not there, then we should discuss how to allow the client to specify the semantics of "equals" for custom types.

**Comment by pixelzoom** [comment]
Why do we need explicit support for Date in deepEquals? (added in 96bd261). A query parameter whose value is a Date would have schema type 'custom'. And I would think that type validation would be handled by the client in isValidValue. If not there, then we should discuss how to allow the client to specify the semantics of "equals" for custom types.

**Comment by samreid** [comment]
I'm ok to drop Date support, I suppose @zepumph and I were thinking if we add Date in the future but deepEqual doesn't support it, it could lead to trouble.

All other deep equals tests are passing.  The lodash dependency is removed.  Can we close this issue?

**Comment by pixelzoom** [comment]
Yep. Let's remove Data from deepEquals, then close.

**Comment by pixelzoom** [comment]
I removed Date. Closing.
