### ISSUE TITLE
nonstandard directory structure for tests

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#26]
axon is typical (similar to dot, kite, scenery):

![screenshot_88](https://cloud.githubusercontent.com/assets/3046552/20894694/b25915ea-bad3-11e6-941f-9e493097744f.png)

query-string-machine has a completely different directory structure:

![screenshot_89](https://cloud.githubusercontent.com/assets/3046552/20894707/c3b437b6-bad3-11e6-9d99-2575c0daa138.png)

• test-query-string-machine.html should be in query-string-machine/tests/qunit/
• testQueryStringMachine.js should be in query-string-machine/tests/qunit/js

**Comment by pixelzoom** [comment]
Files moved, unit tests passing.  @samreid please review.

**Comment by samreid** [comment]
Looks good, closing.
