### ISSUE TITLE
add query-string-machine dependency to documentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#27]
When this repository was created, it became a new dependency for sims.  And a new dependency requires updating the README file for all published sims, and the "Getting Started" section of the PhET Development Overiew. That was not done. And as reported in https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/8oirI03vMrs, this is causing problems for users.

Assigned to @samreid because I believe he created this dependency.

**Comment by pixelzoom** [comment]
When this is fixed, please notify the user at https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/8oirI03vMrs.

**Comment by samreid** [comment]
I fixed this on the google doc and replied to the user, but unfortunately it looks like my reply only went to the user and not the entire group.  I'll take a look and try to remedy this.

**Comment by pixelzoom** [comment]
> I fixed this on the google doc

If that means the PhET Development Overview... It looks like you updated "Getting Started (on Windows)", but missed "Getting Started (on OS X)".

**Comment by samreid** [comment]
I updated the OS X instructions too, and sent a message to the google group.  What is the best way to update all of the READMEs?

**Comment by pixelzoom** [comment]
> What is the best way to update all of the READMEs?

You need to run `grunt published-README` for all sims that have been published. I don't know of any "batch" support for this.

**Comment by samreid** [comment]
OK I'll make a temporary file for chipper/data that lists published sims.  I think I'll search for READMEs that already have "Clone the simulation and its dependencies:" as an indicator.

**Comment by samreid** [comment]
For reference, this grep command seems to work:

`grep -nrw '.' -e "(1) Clone the simulation and its dependencies:" --include \*.md`

**Comment by pixelzoom** [comment]
You could do a local edit of `active-runnables` to include only published sims.  Then run `grunt-all.sh published-README`.

**Comment by samreid** [comment]
Fixed above, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Spot checked a few README.md files, looked at PhET Development Overview, looks good. Closing.
