### ISSUE TITLE
identify query parameters that are for use outside the PhET team

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#30]
In  https://github.com/phetsims/joist/issues/451 we're considering deleting `showHomeScreen` and `screenIndex` query parameters, replacing them with a better interface. In https://github.com/phetsims/joist/issues/451#issuecomment-340593743 we were advised not to change the behavior of the `screens` query parameters, which we've already changed once in #399. 

Going forward, we should be very careful about making query parameters public before they've been vetted through some type of design/review process.

In the meantime:
Which query parameters are intended for public use?
Which query parameters are already in public use?
Do we need some way to annotate/document what's public?

**Comment by pixelzoom** [comment]
Another data point: In #29, 8 query parameters were identified that should have been type flag, but are currently boolean.  Changing them to flag may break client code.

**Comment by pixelzoom** [comment]
Identifying public query parameters is also important for QA.  In some cases (e.g. `showSoluteAmount` in BLL) sims features/functionality are not even visible unless a query parameter is present.

**Comment by pixelzoom** [comment]
Public query parameters in the sims that I'm responsible for:

beers-law-lab: showSoluteAmount, concentrationMeterUnits, beakerUnits, cuvetteSnapInterval
concentration: showSoluteAmount, concentrationMeterUnits, beakerUnits

In the above commit, I've documented that these query parameters are intended for public use.  All other query parameters in my sims are intended for internal use only.

**Comment by pixelzoom** [comment]
11/2/17 dev meeting:

• "External" and "internal" are better adjectives than "public" and "private".
• Assume that all query parameters are for internal use only.
• Mark query parameters that are for external use with a comment in the QSM schema.
• Notify QA that external query parameters need to be tested. 
• Educate the rest of the team about our decisions.

@ariel-phet requested to assign this to him.

**Comment by ariel-phet** [comment]
Discussed with @kathy-phet at status 11/30/2017
