### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by zepumph** [phetsims/query-string-machine#32]
We are going to be exposing QueryStringMachine to PhET-iO clients to use if they see fit. In the phet-io documentation I think it would be best to just point them to the readme for QueryStringMachine on github, rather than to create another, parallel documentation strategy. Tagging @samreid for comment.

EDIT: missed word

**Comment by zepumph** [comment]
From https://github.com/phetsims/phet-io-wrappers/issues/74

**Comment by zepumph** [comment]
@chrisklus do you think this would be something that you would be interested in doing? Documentation is sometimes difficult while still getting your bearings, but it can also be a nice way to learn about this module of the codebase. @samreid please let me know if you think there could be a better way to do this.

**Comment by samreid** [comment]
There is already some high-level documentation at https://github.com/phetsims/query-string-machine/

@zepumph were you picturing adding some smaller more isolated examples like the ones in our wrapper suite?

**Comment by zepumph** [comment]
In general it just is out of date, and incomplete. This is the first sentence:
>Query String parser that supports type coercion, defaults, error checking, etc. based on a schema. Runs in browser or node. Small and only depends on window.assert and _.isEqual.

It does not depend on either of those.

I was picturing:

- [ ] Update the first sentence dependencies
- [ ] Include each public method, a description, and an example (likely much can be copied from the code).
- [ ] some explanation and documentation about (1) what keys are allowed each schema object, and (2) how that changes based on the query parameter "type". Likely this will involve interpreting some of the `TYPES` var into a human readable layout, or at least pointing people to that place in code for that doc (not sure what's best).
- [ ] I think that the large example given is well thought out and thorough, but isn't the easiest starting point for the page. Perhaps adding smaller "getting started" examples at the beginning, probably using `get` rather than `getAll` would be nice.

Does that align with what you were thinking @samreid @chrisklus?

**Comment by zepumph** [comment]
Let me know if you have any more questions @chrisklus.

**Comment by samreid** [comment]
I'm going to work on this for a bit, reassigning and notifying on slack just in case.

**Comment by samreid** [comment]
@chrisklus and I worked on this today.  @zepumph can you please take a look?

**Comment by zepumph** [comment]
This is awesome. Well done folks. Thank you.
