### ISSUE TITLE
Remove lodash usage

### ISSUE THREAD

**Issue by chrisklus** [phetsims/query-string-machine#40]
From https://github.com/phetsims/query-string-machine/issues/39#issuecomment-601901542.

```js
/**
 * Determines if there is a warning for a specified key.
 * @param {string} key
 * @returns {boolean}
 * @public
 */
hasWarning: function( key ) {
  return _.some( this.warnings, warning => warning.key === key );
}
```

In https://github.com/phetsims/joist/issues/593, @pixelzoom and I used lodash for the `hasWarning` function, as @pixelzoom needed the function in NaturalSelectionQueryParameters.js. I'll implement a manual version instead.

**Comment by chrisklus** [comment]
Committed above, @pixelzoom please review.

**Comment by pixelzoom** [comment]
Why do you iterate over all warnings?  This should return as soon as `key` is found.  I.e.:

```js
      hasWarning: function( key ) {
         let hasWarning = false;
         for ( let i = 0; i < this.warnings.length && !hasWarning; i++ ) {
           hasWarning = ( this.warning[ i ].key === key );
         }
         return hasWarning;
      }
```

**Comment by chrisklus** [comment]
Thanks, fixed above.

**Comment by pixelzoom** [comment]
👍 Testing in Natural Selection. Closing.
