### ISSUE TITLE
allow "public: true" for 'flag' query parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#41]
Over in https://github.com/phetsims/aqua/issues/91, we said that we should indicate which query parameters are public by adding `public: true` to their schema.  This causes their value to be validated, and (if there's an error) shows a friendly error dialog. 

`public: true` currently does not work for query parameters of `type 'flag'`, probably because they don't have a value to validate.  @chrisklus and I discussed via Slack, and decided it would be nice to support `public: true` for all query parameter types, to identify which are intended to be public-facing, make it easy to document in the CRC, and to make it easy to locate all public-facing query parameters by searching for "public:" in *QueryParameters.js.

@chrisklus has volunteered to make it so.

**Comment by pixelzoom** [comment]
@chrisklus when you've completed this, please assign back to me.  I'd like to use this for: 
- [ ] `BLLQueryParameters.showSoluteAmount`
- [ ] `PHScaleQueryParameters.showRatio`

**Comment by chrisklus** [comment]
All set - please review while addressing your sims if you don't mind.

**Comment by pixelzoom** [comment]
Looks great, thanks!  I added to my query parameters.  Closing.
