### ISSUE TITLE
Array should provide elementSchema

### ISSUE THREAD

**Issue by samreid** [phetsims/query-string-machine#5]
To simplify things, Array should provide elementSchema.  We will have to change how schemas are validated, but this will be a simpler interface.

**Comment by samreid** [comment]
`allowedValues` may make sense for some array elements, though seems like it may have limited use.  `defaultValue` makes no sense for array elements and may make this not possible.

Would `elementSchema` allow us to simplify the implementation, or support arbitrary types (like arrays of arrays of number?)

Here's an example:
```js
// a 2-dimensional array of numbers 1-4
height: {
 type: 'array',
 separator: '+',
 elementSchema:{
  type:'array',
  separator: ',',
  elementSchema:{
   type: 'number',
   allowedValues: [1,2,3,4] 
 }
}
```

I'm not sure whether to proceed with this or not.

**Comment by samreid** [comment]
I added element schemas to array and it worked out nicely, I added a sample test for 2d-array of number and it is working well too.  @pixelzoom can you take a look as part of your review?

**Comment by pixelzoom** [comment]
Looking at the test harness (test-query-string-machine.html), it looks like we have different ideas about the semantics of `allowedValues` for type 'array'.   I was thinking that this would enumerate the values that were allowed to be in the array, not the possible arrays of values. 

For example, with this schema for parameter `primes`:

```js
screens: {
      type: 'array',
      elementSchema: {
        type: 'number'
      },
      defaultValue: []
      allowedValues: [ 1, 3, 5, 7, 11, 13 ]
    }
```

This would be valid: `?primes=1,5,11`

**Comment by samreid** [comment]
To specify the allowed values for elements in an array, use elementSchema.allowedValues.  Something like:

```js
   screens: {
      type: 'array',
      elementSchema: {
        type: 'number',
        allowedValues: [ 1, 3, 5, 7, 11, 13 ]
      },
      defaultValue: []
    }
```

**Comment by pixelzoom** [comment]
Ah, got it.  Closing.
