### ISSUE TITLE
Query Parameters in Teacher Tips, specially in translated teacher tips. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/query-string-machine#52]
@solaolateju  and I discussed today's Query Parameter in the teacher tips. We decided that it is important that the English version includes a good description of how to use them with the URL that teachers get when they go to the PhET website, especially when the sim is in a specific locale. Originally, I was thinking of adding something only for translated teacher tips, but Sola showed me that most of the translators don't have the technical background to understand Query Parameter and take a decision to include something that is not included in the English version of the document. Most of the translators, just translate. Designers create teacher tips then this is a decision that needs your input. @pixelzoom commented that this is an open question not only for teacher tips #46 .

**Comment by arouinfar** [comment]
We discussed this at the 7/6/23 design meeting. @kathy-phet @DianaTavares @solaolateju @catherinecarter and I were present. Based on the discussion, @DianaTavares mocked up some changes to the Customization Options section, and I made some further edits.

Here's what it looks like in the context of the [Teacher Tips template](https://github.com/phetsims/query-string-machine/files/12006168/sim-name-guide-template.pdf). Note that this includes a variety of examples from different sims to illustrate all of the possible common code query parameters.

<img width="600" alt="Screen Shot 2023-07-10 at 10 59 18 AM" src="https://github.com/phetsims/query-string-machine/assets/8419308/d0990971-5d22-4422-84be-260bf3a0e870">


Open questions:
* Does the information before the table more clearly explain how to use query parameters?
* We included the `locale` query parameter in the table. Is it adequately documented? (Refer to PDF to review links.)
* Should we be concerned about the delay between initial publication and translations? Translators are usually pretty quick, and Spanish seems like a safe examplar locale.
* What is the priority for updating existing teacher tips?

**Comment by kathy-phet** [comment]
Overall - looks like a great improvement! Some edits/suggestions: 
- 1st sentence - "can added" to "can be added" 
- I would put the sentence about what the gear means before the table - instead of at the end of the table. 
- I thought of one other general query parameter we should share with all teachers "allowLinks=false" (I think that is the right syntax)
- under locale I would say "can be found on the simulation page, under the "Translations" tab."

I'm not worried about not having Spanish available. It is quick. 

Sola wants the teacher tips updated for Translators. @solaolateju - would you have time/capacity to do the updates yourself once all of this is finalized.

**Comment by kathy-phet** [comment]
Maybe one other suggestion to consider, would be to divide the quary parmeter into sections - sim-specific and general?

**Comment by arouinfar** [comment]
Thanks for the feedback @kathy-phet. I incorporated your comments in https://github.com/phetsims/query-string-machine/issues/52#issuecomment-1629716841.  I also mocked up the options where we divide things up into two tables, but that adds quite a bit of extra length. It may also imply that the general query parameters apply to all sims, which isn't technically correct. I would prefer to keep it all in one table.

<img width="600" alt="Screen Shot 2023-07-11 at 2 46 18 PM" src="https://github.com/phetsims/query-string-machine/assets/8419308/13d6d0e3-0815-470b-b9a2-91bc7a1ff0ea">


<img width="600" alt="Screen Shot 2023-07-11 at 2 43 27 PM" src="https://github.com/phetsims/query-string-machine/assets/8419308/4c580f55-377f-45d6-9056-036b97dd8cc3">

**Comment by DianaTavares** [comment]
I like the idea of the two tables! And a description of what the mesh means. But I think that wilt only one description of the mesh is enough, not one in each table.

**Comment by DianaTavares** [comment]
Notes about the design meeting (July 13):

- @Sola is going to lead that work. 
- Create a spreadsheet, to get started updating the files with QA support to track work. For the table to have a column Sim, list of QP, the status of the teacher tip document. This can be tacked for "metadata". Train the QA team to do this work. 
- If a sim doesn't have a table, and it is a new query parameter, contact the designer to support the description.
- Translators of teacher tips can continue doing their work, and have a database to manually notify them, that a teacher tip has been updated

**Comment by arouinfar** [comment]
The updated Teacher Tips template can be found [on SharePoint](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Teaching%20Resources%2FTeacher%20Tips%2FHTML5%20Teacher%20Tips%20templates&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa) under PhET Files > PhET Teaching Resources > Teacher Tips > HTML5 Teacher Tips template.

> Create a spreadsheet, to get started updating the files with QA support to track work. 

@solaolateju shared a spreadsheet with me, which I will review.

**Comment by kathy-phet** [comment]
@arouinfar I forgot to add my comments. I'll do that by Monday and you can decide if it's worth updating the template

**Comment by arouinfar** [comment]
I worked with @Nancy-Salpepi to modify the spreadsheet @solaolateju created and made a checklist for QA to follow when updating teacher tips. We will track this work in https://github.com/phetsims/qa/issues/963.

@kathy-phet it's not too late to make changes to the template. I slacked you a PDF of the latest template. Please let me know what changes you'd like me to make by tomorrow morning so QA can get started.

**Comment by arouinfar** [comment]
@kathy-phet and I made the updates to template, and it's been updated on SharePoint. Next steps are being tracked in https://github.com/phetsims/qa/issues/963, closing.
